import Head from 'next/head'
import { UserAuth } from '../context/AuthContext'
import Link from 'next/link'
import { auth } from '../firebase'
import { useEffect } from 'react'
import Router, { useRouter } from 'next/router'
export default function Home() {
  const router = useRouter()
  const { user, logout } = UserAuth()
  console.log(user + 'user')

  useEffect(() => {
    if (!user?.uid) {
      router.push('/login')
    }
  }, [router, user?.uid])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <button className='btn btn-primary' onClick={() => logout(auth)}>
        Click here
      </button>
      <p>Hello {user?.email}</p>
    </div>
  )
}
