import Head from 'next/head'
import { UserAuth } from '../context/AuthContext'
import Link from 'next/link'
import { auth, db } from '../firebase'
import { useEffect } from 'react'
import Router, { useRouter } from 'next/router'
import { useTheme } from 'next-themes'
import { doc, getDoc } from 'firebase/firestore'

export default function Home() {
  const router = useRouter()
  const { user, logout } = UserAuth()
  console.log(user)

  const { theme, setTheme } = useTheme()
  console.log(theme)

  useEffect(() => {
    const getUserDoc = async () => {
      if (user?.uid) {
        const docRef = doc(db, 'users', user?.uid)
        const docSnap = await getDoc(docRef)

        if (docSnap.exists()) {
          setTheme(docSnap.data().theme)
        } else {
          // doc.data() will be undefined in this case
          console.log('No such document!')
        }
      }
    }
    getUserDoc()

    if (!user?.uid) {
      router.push('/login')
    }
  }, [router, user?.uid, setTheme])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </div>
  )
}
