import Head from 'next/head'
import { UserAuth } from '../context/AuthContext'
import Link from 'next/link'
import { auth, db } from '../firebase'
import { useEffect, useState } from 'react'
import Router, { useRouter } from 'next/router'
import { useTheme } from 'next-themes'
import { doc, getDoc, onSnapshot } from 'firebase/firestore'
import { BsPlusCircleDotted } from 'react-icons/bs'
import SnipDisplay from '../components/SnipDisplay'

export default function Home() {
  const router = useRouter()
  const { user, logout, updateSnips, snips } = UserAuth()
  console.log(user)

  const { theme, setTheme } = useTheme()
  console.log(theme)

  useEffect(() => {
    const getUserDoc = async () => {
      if (user?.uid) {
        const docRef = doc(db, 'users', user?.uid)
        // const docSnap = await getDoc(docRef)
        const docSnap = onSnapshot(docRef, (doc) => {
          console.log('Current Data: ', doc.data())
          setTheme(doc.data().theme)
          updateSnips(doc.data().snips)
        })

        // if (docSnap.exists()) {
        //   setTheme(docSnap.data().theme)
        //   updateSnips(docSnap.data().snips)
        // } else {
        // doc.data() will be undefined in this case
        //   console.log('No such document!')
        // }
      }
    }
    getUserDoc()

    if (!user?.uid) {
      router.push('/login')
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [router, user?.uid, setTheme])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='flex justify-center flex-col items-center mt-10 max-w-4xl w-10/12 mx-auto'>
        <h1 className='text-6xl font-semibold'>Snips!</h1>
        <p className='text-2xl mt-5 text-center'>
          Create new Snippets to save for later or reuse Snippets from the past
          to save time.
        </p>
        <Link href='/snips'>
          <button className='btn btn-primary btn-lg flex gap-2 text-xl mt-10'>
            Snip
            <BsPlusCircleDotted className='text-2xl' />
          </button>
        </Link>
        {snips && <SnipDisplay snips={snips} />}
      </main>
    </div>
  )
}
